# Load the dataset

In [64]:
import pandas as pd

raw_df = pd.read_excel(
    "../1_datasets/raw_data/IRENA_OFGStats.raw.xlsx", sheet_name="data"
)
df = raw_df.copy()
df.head()

,Region,UN Sub-region,Country,IRENA Label,ISO Code,Flow,Group Technology,Sub-Technology,Technology,Product Code,DataType,Value,Unit,Year,Ptype,Publication
0,Africa,Sub-Saharan Africa,Angola,Angola,AGO,Off-grid capacity,Solar energy,Solar PV (Others),Other off-grid solar PV,24129.0,ELECCAP,0.0,MW,2000,220,2024 OFG RE Statistics
1,Africa,Sub-Saharan Africa,Angola,Angola,AGO,Off-grid capacity,Solar energy,Solar PV (Others),Other off-grid solar PV,24129.0,ELECCAP,0.0,MW,2001,220,2024 OFG RE Statistics
2,Africa,Sub-Saharan Africa,Angola,Angola,AGO,Off-grid capacity,Solar energy,Solar PV (Others),Other off-grid solar PV,24129.0,ELECCAP,0.0,MW,2002,220,2024 OFG RE Statistics
3,Africa,Sub-Saharan Africa,Angola,Angola,AGO,Off-grid capacity,Solar energy,Solar PV (Others),Other off-grid solar PV,24129.0,ELECCAP,0.0,MW,2003,220,2024 OFG RE Statistics
4,Africa,Sub-Saharan Africa,Angola,Angola,AGO,Off-grid capacity,Solar energy,Solar PV (Others),Other off-grid solar PV,24129.0,ELECCAP,0.0,MW,2004,220,2024 OFG RE Statistics

In [65]:
df.info()
df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52343 entries, 0 to 52342
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Region            52343 non-null  object
 1   UN Sub-region     52343 non-null  object
 2   Country           52343 non-null  object
 3   IRENA Label       52343 non-null  object
 4   ISO Code          52343 non-null  object
 5   Flow              52343 non-null  object
 6   Group Technology  52343 non-null  object
 7   Sub-Technology    52343 non-null  object
 8   Technology        52343 non-null  object
 9   Product Code      51205 non-null  float64
 10  DataType          52343 non-null  object
 11  Value             52321 non-null  float64
 12  Unit              52343 non-null  object
 13  Year              52343 non-null  int64
 14  Ptype             52343 non-null  int64
 15  Publication       52343 non-null  object
dtypes: float64(2), int64(2), object(12)
memory usage: 6.4+ MB

(52343, 16)

In [66]:
df.isnull().sum()

Region                 0
UN Sub-region          0
Country                0
IRENA Label            0
ISO Code               0
Flow                   0
Group Technology       0
Sub-Technology         0
Technology             0
Product Code        1138
DataType               0
Value                 22
Unit                   0
Year                   0
Ptype                  0
Publication            0
dtype: int64

- **It's clear that there are a lot of null values in the product Code but the column itself is not relevant to our study so it will be dropped along with: UN Sub-region, IRENA Label, Ptype, and publication**

In [67]:
df.drop(
    [
        "UN Sub-region",
        "IRENA Label",
        "Ptype",
        "Publication",
        "Product Code",
        "DataType",
    ],
    axis=1,
    inplace=True,
)

In [68]:
df.head()

,Region,Country,ISO Code,Flow,Group Technology,Sub-Technology,Technology,Value,Unit,Year
0,Africa,Angola,AGO,Off-grid capacity,Solar energy,Solar PV (Others),Other off-grid solar PV,0.0,MW,2000
1,Africa,Angola,AGO,Off-grid capacity,Solar energy,Solar PV (Others),Other off-grid solar PV,0.0,MW,2001
2,Africa,Angola,AGO,Off-grid capacity,Solar energy,Solar PV (Others),Other off-grid solar PV,0.0,MW,2002
3,Africa,Angola,AGO,Off-grid capacity,Solar energy,Solar PV (Others),Other off-grid solar PV,0.0,MW,2003
4,Africa,Angola,AGO,Off-grid capacity,Solar energy,Solar PV (Others),Other off-grid solar PV,0.0,MW,2004

- **Now, we should handle the 22 missing values in the "Value" Column**

In [69]:
missing_rows = df[df["Value"].isnull()]
missing_rows

,Region,Country,ISO Code,Flow,Group Technology,Sub-Technology,Technology,Value,Unit,Year
39940,Central America and the Caribbean,Bahamas (the),BHS,Off-grid capacity,Solar energy,Solar lights and SHS,Solar lights and solar home systems (SHS),NaN,MW,2023
39946,Central America and the Caribbean,Belize,BLZ,Off-grid capacity,Solar energy,Solar lights and SHS,Solar lights and solar home systems (SHS),NaN,MW,2023
39957,Central America and the Caribbean,Costa Rica,CRI,Off-grid capacity,Solar energy,Solar lights and SHS,Solar lights and solar home systems (SHS),NaN,MW,2023
39971,Central America and the Caribbean,Dominica,DMA,Off-grid capacity,Solar energy,Solar lights and SHS,Solar lights and solar home systems (SHS),NaN,MW,2023
40021,Central America and the Caribbean,Nicaragua,NIC,Off-grid capacity,Solar energy,Solar lights and SHS,Solar lights and solar home systems (SHS),NaN,MW,2023
40035,Central America and the Caribbean,Puerto Rico,PRI,Off-grid capacity,Solar energy,Solar lights and SHS,Solar lights and solar home systems (SHS),NaN,MW,2023
40082,South America,Brazil,BRA,Off-grid capacity,Solar energy,Solar lights and SHS,Solar lights and solar home systems (SHS),NaN,MW,2023
40089,South America,Chile,CHL,Off-grid capacity,Solar energy,Solar lights and SHS,Solar lights and solar home systems (SHS),NaN,MW,2023
40141,Africa,Egypt,EGY,Off-grid capacity,Solar energy,Solar lights and SHS,Solar lights and solar home systems (SHS),NaN,MW,2023
40169,Africa,Sudan (the),SDN,Off-grid capacity,Solar energy,Solar lights and SHS,Solar lights and solar home systems (SHS),NaN,MW,2023
40209,Middle East,Jordan,JOR,Off-grid capacity,Solar energy,Solar lights and SHS,Solar lights and solar home systems (SHS),NaN,MW,2023
40283,Oceania,Kiribati,KIR,Off-grid capacity,Solar energy,Solar lights and SHS,Solar lights and solar home systems (SHS),NaN,MW,2023
40293,Oceania,Marshall Islands (the),MHL,Off-grid capacity,Solar energy,Solar lights and SHS,Solar lights and solar home systems (SHS),NaN,MW,2023
40303,Oceania,Nauru,NRU,Off-grid capacity,Solar energy,Solar lights and SHS,Solar lights and solar home systems (SHS),NaN,MW,2023
40309,Oceania,Palau,PLW,Off-grid capacity,Solar energy,Solar lights and SHS,Solar lights and solar home systems (SHS),NaN,MW,2023
40330,Oceania,Samoa,WSM,Off-grid capacity,Solar energy,Solar lights and SHS,Solar lights and solar home systems (SHS),NaN,MW,2023
40352,Oceania,Tonga,TON,Off-grid capacity,Solar energy,Solar lights and SHS,Solar lights and solar home systems (SHS),NaN,MW,2023
40427,Asia,Lao People's Democratic Republic (the),LAO,Off-grid capacity,Solar energy,Solar lights and SHS,Solar lights and solar home systems (SHS),NaN,MW,2023
40522,Asia,Bhutan,BTN,Off-grid capacity,Solar energy,Solar lights and SHS,Solar lights and solar home systems (SHS),NaN,MW,2023
43089,Africa,Cabo Verde,CPV,Off-grid capacity,Solar energy,Solar lights and SHS,Solar lights and solar home systems (SHS),NaN,MW,2023
43157,Africa,Equatorial Guinea,GNQ,Off-grid capacity,Solar energy,Solar lights and SHS,Solar lights and solar home systems (SHS),NaN,MW,2023
43308,Africa,Mauritania,MRT,Off-grid capacity,Solar energy,Solar lights and SHS,Solar lights and solar home systems (SHS),NaN,MW,2023

- **So, it's apparent that most of the missing values here are from countries out of our scope, so it's better to just fill the null values with zeros**

# Filling the missing values with zeros

In [70]:
df2 = df.fillna(value=0)
df2.isnull().sum().sum()

np.int64(0)

**- Now, let's checkup the year range, our research study is from 2000 onward**

In [71]:
df2["Year"].unique()

array([2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010,
       2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021,
       2022, 2023])

- **Now, we can add a conflict status column to the dataset to present whether a country experienced conflicts in the predefined period or not.**

In [72]:
conflict_countries = [
    "Syria",
    "Iraq",
    "Sudan (the)",
    "South Sudan",
    "Palestine",
    "Mali",
    "Ethiopia",
    "Ukraine",
    "Yemen",
    "Libya",
    "Afghanistan",
    "Nigeria",
    "Central African Republic",
    "Somalia",
    "Pakistan",
    "Mozambique",
    "Myanmar",
    "Chad",
    "Democratic Republic of the Congo (the)",
]
df2["Conflict Status"] = df2["Country"].apply(
    lambda x: "Conflict" if x in conflict_countries else "No Conflict"
)
df2.head(10)

,Region,Country,ISO Code,Flow,Group Technology,Sub-Technology,Technology,Value,Unit,Year,Conflict Status
0,Africa,Angola,AGO,Off-grid capacity,Solar energy,Solar PV (Others),Other off-grid solar PV,0.0,MW,2000,No Conflict
1,Africa,Angola,AGO,Off-grid capacity,Solar energy,Solar PV (Others),Other off-grid solar PV,0.0,MW,2001,No Conflict
2,Africa,Angola,AGO,Off-grid capacity,Solar energy,Solar PV (Others),Other off-grid solar PV,0.0,MW,2002,No Conflict
3,Africa,Angola,AGO,Off-grid capacity,Solar energy,Solar PV (Others),Other off-grid solar PV,0.0,MW,2003,No Conflict
4,Africa,Angola,AGO,Off-grid capacity,Solar energy,Solar PV (Others),Other off-grid solar PV,0.0,MW,2004,No Conflict
5,Africa,Angola,AGO,Off-grid capacity,Solar energy,Solar PV (Others),Other off-grid solar PV,0.0,MW,2005,No Conflict
6,Africa,Angola,AGO,Off-grid capacity,Solar energy,Solar PV (Others),Other off-grid solar PV,0.0,MW,2006,No Conflict
7,Africa,Angola,AGO,Off-grid capacity,Solar energy,Solar PV (Others),Other off-grid solar PV,0.0,MW,2007,No Conflict
8,Africa,Angola,AGO,Off-grid capacity,Solar energy,Solar PV (Others),Other off-grid solar PV,0.0,MW,2008,No Conflict
9,Africa,Angola,AGO,Off-grid capacity,Solar energy,Solar PV (Others),Other off-grid solar PV,0.0,MW,2009,No Conflict

- **let's check if all the unit in the `Unit` column are the same**

In [73]:
df2["Unit"].unique()

array(['MW', 'Thousands', '1,000 m3'], dtype=object)

- Hmm, that's interesting, we have to somehow standardize the value units

In [74]:
df2[df2["Unit"] == "1,000 m3"]

,Region,Country,ISO Code,Flow,Group Technology,Sub-Technology,Technology,Value,Unit,Year,Conflict Status
11271,Africa,Burundi,BDI,Off-grid biogas production,Bioenergy,Biogas production,Production of biogas for industry,0.0000,"1,000 m3",2000,No Conflict
11272,Africa,Burundi,BDI,Off-grid biogas production,Bioenergy,Biogas production,Production of biogas for industry,0.0000,"1,000 m3",2001,No Conflict
11273,Africa,Burundi,BDI,Off-grid biogas production,Bioenergy,Biogas production,Production of biogas for industry,0.0000,"1,000 m3",2002,No Conflict
11274,Africa,Burundi,BDI,Off-grid biogas production,Bioenergy,Biogas production,Production of biogas for industry,0.0000,"1,000 m3",2003,No Conflict
11275,Africa,Burundi,BDI,Off-grid biogas production,Bioenergy,Biogas production,Production of biogas for industry,0.0000,"1,000 m3",2004,No Conflict
...,...,...,...,...,...,...,...,...,...,...,...
34763,Africa,Zimbabwe,ZWE,Off-grid biogas production,Bioenergy,Biogas production,Total biogas production,1148.0810,"1,000 m3",2019,No Conflict
34764,Africa,Zimbabwe,ZWE,Off-grid biogas production,Bioenergy,Biogas production,Total biogas production,1142.4995,"1,000 m3",2020,No Conflict
34765,Africa,Zimbabwe,ZWE,Off-grid biogas production,Bioenergy,Biogas production,Total biogas production,1135.5455,"1,000 m3",2021,No Conflict
34766,Africa,Zimbabwe,ZWE,Off-grid biogas production,Bioenergy,Biogas production,Total biogas production,1055.3000,"1,000 m3",2022,No Conflict
34767,Africa,Zimbabwe,ZWE,Off-grid biogas production,Bioenergy,Biogas production,Total biogas production,1055.3000,"1,000 m3",2023,No Conflict

In [75]:
conflict_m3 = df2[
    (df2["Country"].isin(conflict_countries)) & (df2["Unit"] == "1,000 m3")
]
Countries_value_bigger_zero = conflict_m3[conflict_m3["Value"] > 0]["Country"].unique()
Countries_value_bigger_zero

array(['Iraq', 'Myanmar', 'Afghanistan', 'Pakistan', 'Nigeria',
       'Mozambique', 'Mali', 'Democratic Republic of the Congo (the)',
       'Ethiopia'], dtype=object)

In [76]:
conflict_m3.head()

,Region,Country,ISO Code,Flow,Group Technology,Sub-Technology,Technology,Value,Unit,Year,Conflict Status
11324,Africa,Nigeria,NGA,Off-grid biogas production,Bioenergy,Biogas production,Production of biogas for industry,0.0,"1,000 m3",2000,Conflict
11325,Africa,Nigeria,NGA,Off-grid biogas production,Bioenergy,Biogas production,Production of biogas for industry,0.0,"1,000 m3",2001,Conflict
11326,Africa,Nigeria,NGA,Off-grid biogas production,Bioenergy,Biogas production,Production of biogas for industry,0.0,"1,000 m3",2002,Conflict
11327,Africa,Nigeria,NGA,Off-grid biogas production,Bioenergy,Biogas production,Production of biogas for industry,0.0,"1,000 m3",2003,Conflict
11328,Africa,Nigeria,NGA,Off-grid biogas production,Bioenergy,Biogas production,Production of biogas for industry,0.0,"1,000 m3",2004,Conflict

- The `1000 m3` unit is appeared to be primarily used for `Biogass` technology, which is irrelevant to us

In [77]:
df2.groupby(["Flow", "Unit"])["Technology"].count()

Flow                        Unit
Off-grid biogas production  1,000 m3      4632
Off-grid capacity           MW           33130
Off-grid energy access      Thousands    14581
Name: Technology, dtype: int64

In [78]:
df2 = df2[~df2["Sub-Technology"].str.contains("biogas", case=False, na=False)]
df2 = df2[df2["Group Technology"] != "Bioenergy"]

In [79]:
df2.groupby(["Flow", "Unit"])["Technology"].count()

Flow                    Unit
Off-grid capacity       MW           31594
Off-grid energy access  Thousands    13224
Name: Technology, dtype: int64

In [80]:
df2.sample(10)

,Region,Country,ISO Code,Flow,Group Technology,Sub-Technology,Technology,Value,Unit,Year,Conflict Status
48093,Oceania,Marshall Islands (the),MHL,Off-grid capacity,Solar energy,Solar PV (Communication),Other off-grid solar PV (of which communication),0.06000,MW,2011,No Conflict
41864,Asia,Myanmar,MMR,Off-grid capacity,Solar energy,Solar home systems,Solar home systems (SHS >50 W),3.36687,MW,2014,Conflict
23008,Central America and the Caribbean,Belize,BLZ,Off-grid capacity,Solar energy,Solar pumps,Solar pumps,0.00000,MW,2007,No Conflict
19906,Oceania,Cook Islands (the),COK,Off-grid capacity,Solar energy,Solar mini-grids,Solar mini-grids,0.00000,MW,2006,No Conflict
18281,Asia,Maldives,MDV,Off-grid energy access,Solar energy,Solar mini-grids,Number of people connected to solar mini-grids...,0.00000,Thousands,2010,No Conflict
43719,Africa,Namibia,NAM,Off-grid capacity,Solar energy,Solar home systems,Solar home systems (SHS 11-50 W),0.00873,MW,2021,No Conflict
8795,Africa,Niger (the),NER,Off-grid energy access,Solar energy,Solar mini-grids,Number of people connected to solar mini-grids...,0.00000,Thousands,2000,No Conflict
20322,South America,Venezuela (Bolivarian Republic of),VEN,Off-grid capacity,Solar energy,Solar mini-grids,Solar mini-grids,0.00000,MW,2009,No Conflict
46593,Africa,Gabon,GAB,Off-grid capacity,Solar energy,Solar pumps,Solar pumps,0.02020,MW,2014,No Conflict
7153,Africa,Angola,AGO,Off-grid energy access,Solar energy,Solar lights,Number of people using solar lights (<11 W),0.00000,Thousands,2012,No Conflict

- The 'value column in the dataframe has two different unrelated units, in our case, it is better to split the dataframe

In [81]:
# Filter for MW (capacity)
df_mw = df2[df2["Unit"] == "MW"].copy()
# Filter for thousands (people served)
df_thousands = df2[df2["Unit"] == "Thousands"].copy()

In [82]:
print(df_mw.groupby(["Flow", "Unit"])["Technology"].count())
print(df_thousands.groupby(["Flow", "Unit"])["Technology"].count())

Flow               Unit
Off-grid capacity  MW      31594
Name: Technology, dtype: int64
Flow                    Unit
Off-grid energy access  Thousands    13224
Name: Technology, dtype: int64

In [83]:
df_mw["Sub-Technology"].unique()

array(['Solar PV (Others)', 'Solar PV (Health)',
       'Solar PV (Commercial/Public)', 'Solar PV (Education)',
       'Solar PV (Not specified)', 'Solar PV (Industry)',
       'Solar PV (Tourism)', 'Solar PV (Public lighting)',
       'Solar PV (Communication)', 'Solar PV (Residential)',
       'Solar PV (Agriculture)', 'Solar PV (Multi-purpose)',
       'Solar mini-grids', 'Solar lights', 'Solar pumps',
       'Solar home systems', 'Onshore wind energy', 'Hydropower',
       'Solar cookers', 'Solar lights and SHS'], dtype=object)

In [84]:
df_thousands["Sub-Technology"].unique()

array(['Hydropower', 'Solar lights', 'Solar mini-grids',
       'Solar home systems', 'Solar cookers'], dtype=object)

In [85]:
df_mw.head()

,Region,Country,ISO Code,Flow,Group Technology,Sub-Technology,Technology,Value,Unit,Year,Conflict Status
0,Africa,Angola,AGO,Off-grid capacity,Solar energy,Solar PV (Others),Other off-grid solar PV,0.0,MW,2000,No Conflict
1,Africa,Angola,AGO,Off-grid capacity,Solar energy,Solar PV (Others),Other off-grid solar PV,0.0,MW,2001,No Conflict
2,Africa,Angola,AGO,Off-grid capacity,Solar energy,Solar PV (Others),Other off-grid solar PV,0.0,MW,2002,No Conflict
3,Africa,Angola,AGO,Off-grid capacity,Solar energy,Solar PV (Others),Other off-grid solar PV,0.0,MW,2003,No Conflict
4,Africa,Angola,AGO,Off-grid capacity,Solar energy,Solar PV (Others),Other off-grid solar PV,0.0,MW,2004,No Conflict

In [86]:
df_thousands.head()

,Region,Country,ISO Code,Flow,Group Technology,Sub-Technology,Technology,Value,Unit,Year,Conflict Status
7003,Africa,Cameroon,CMR,Off-grid energy access,Hydropower (excl. Pumped Storage),Hydropower,Number of people connected to hydropower,0.0,Thousands,2000,No Conflict
7004,Africa,Cameroon,CMR,Off-grid energy access,Hydropower (excl. Pumped Storage),Hydropower,Number of people connected to hydropower,0.0,Thousands,2001,No Conflict
7005,Africa,Cameroon,CMR,Off-grid energy access,Hydropower (excl. Pumped Storage),Hydropower,Number of people connected to hydropower,0.0,Thousands,2002,No Conflict
7006,Africa,Cameroon,CMR,Off-grid energy access,Hydropower (excl. Pumped Storage),Hydropower,Number of people connected to hydropower,0.0,Thousands,2003,No Conflict
7007,Africa,Democratic Republic of the Congo (the),COD,Off-grid energy access,Hydropower (excl. Pumped Storage),Hydropower,Number of people connected to hydropower,0.0,Thousands,2000,Conflict

- **Now, The resultant datasets will be saved to "cleaned_data" sub-folder in the "1_dataset" folder**

In [87]:
df_mw.to_excel(
    "../1_datasets/cleaned_data/IRENA_OFGStats_mw.cleaned.xlsx",
    sheet_name="Cleaned_data",
    index=False,
)

In [88]:
df_thousands.to_excel(
    "../1_datasets/cleaned_data/IRENA_OFGStats_thousands.cleaned.xlsx",
    sheet_name="Cleaned_data",
    index=False,
)